// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDobmSrkWxSsgBn51YngJGnuiKlvzPHps',
    appId: '1:249465656547:web:0cfee75d8962216382e1d6',
    messagingSenderId: '249465656547',
    projectId: 'chat-app-980b7',
    authDomain: 'chat-app-980b7.firebaseapp.com',
    storageBucket: 'chat-app-980b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLNyK4V1PlLa6fRxsrAfkUefkuf1yEAi8',
    appId: '1:249465656547:android:874aea07c25e987e82e1d6',
    messagingSenderId: '249465656547',
    projectId: 'chat-app-980b7',
    storageBucket: 'chat-app-980b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzmZaXtMOi1zMgCg1Wt1eqqHw_rIAuQBc',
    appId: '1:249465656547:ios:0d376eb87d7866a582e1d6',
    messagingSenderId: '249465656547',
    projectId: 'chat-app-980b7',
    storageBucket: 'chat-app-980b7.appspot.com',
    iosClientId: '249465656547-g1li3c9s968chv74gp5dqatjifijmskt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzmZaXtMOi1zMgCg1Wt1eqqHw_rIAuQBc',
    appId: '1:249465656547:ios:79c7f5f4799f4fc082e1d6',
    messagingSenderId: '249465656547',
    projectId: 'chat-app-980b7',
    storageBucket: 'chat-app-980b7.appspot.com',
    iosClientId: '249465656547-d19eg1tad7ta7a1hh59t8gfqpmct8kn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
